name: Check branch convention usage
on:
  pull_request:
    types: [opened, reopened]

jobs:
  branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check the branch convention usage
        uses: duart38/branch-convention-check@v2.1.0
        with:
          ignore_branch_check: '(dependabot\/.*)'
          ignore: 'main'